--- #YAML:1.0
name:                App-BCVI-NotifyClient
version:             1.00
abstract:            Send a notification message back to the user's desktop
license:             ~
author:              
    - Grant McLean <grantm@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
